### ISSUE TITLE
KeyError issue

### ISSUE THREAD

**Issue by AlexRaeside** [felicityallen/JACKS#6]
Hi,

Whenever I have tried to run jacks i keep getting a key issue error
Here is the error code

[2019-05-23 16:36:55,172] jacks: INFO     Loading sample specification
[2019-05-23 16:36:55,172] jacks: INFO     Loading gene mappings
[2019-05-23 16:36:55,186] jacks: INFO     Loading data and pre-processing
Traceback (most recent call last):
  File "/home/alexander/bioTools/JACKS/jacks/run_JACKS.py", line 7, in <module>
    runJACKSFromArgs()
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 441, in runJACKSFromArgs
    args.outprefix, args.reffile, args.n_pseudo, args.count_prior)
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 431, in runJACKS
    outprefix, apply_w_hp=apply_w_hp, norm_type=norm_type, ctrl_genes=ctrl_genes, fdr=fdr, fdr_thresh_type=fdr_thresh_type, n_pseudo=n_pseudo, count_prior=count_prior )
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 383, in load_data_and_run
    data, meta, sample_ids, genes, gene_index = loadDataAndPreprocess(sample_spec, gene_spec,ctrl_spec=ctrl_spec,normtype=norm_type, ctrl_geneset=ctrl_geneset, prior=count_prior)
  File "/home/alexander/bioTools/JACKS/jacks/jacks/preprocess.py", line 147, in loadDataAndPreprocess
    counts.append([np.log2(eval(row[colname])+prior) for sample_id, colname in sample_spec[filename]])
  File "/home/alexander/bioTools/JACKS/jacks/jacks/preprocess.py", line 147, in <listcomp>
    counts.append([np.log2(eval(row[colname])+prior) for sample_id, colname in sample_spec[filename]])
KeyError: 'd15Cas9k2'

Here is a copy of the input

python ~/bioTools/JACKS/jacks/run_JACKS.py smallCount.tab smallRep.tab guideMapping.tab --ctrl_sample_hdr=Control

Here is what the smallRep.tab looks like

Replicate	Sample	Control
d15Cas9k1	d15Cas9	d15Wt
d15Cas9k2	d15Cas9	d15Wt
d15WTk1	d15Wt	d15Wt
d15WTk2	d15Wt	d15Wt

Here is a sample of the smallCount.tab file 

sgRNA	d15Cas9k1	d15Cas9k2 	d15WTk1	d15WTk2
PMVK_NM_006556.3_154936638	3214	3573	4319	4463
PLK2_NM_006622.3_58457530	6003	5871	8658	6865
CHEK1_NM_001114121.2_125627805	3948	2687	5182	5021
MAP4K5_NM_006575.4_50485610	3688	3408	5612	5653
CKS2_NM_001827.2_89311315	6709	7779	9329	8668
AK4_NM_013410.3_65148450	5115	4971	6398	6486

An help would be deeply appreciated.
Thank you.

**Comment by AlexRaeside** [comment]
The previous commit version appears to work great

**Comment by felicityallen** [comment]
Sorry to hear it's not working for you.  Looks ok to me and making files out of the above works for me. Are the columns in your files tab separated? Would you mind uploading smallCount.tab smallRep.tab and guideMapping.tab so i can try to reproduce?

**Comment by felicityallen** [comment]
Previous commit was a really minor change (correction to an error message you're not getting), so should not have affected anything.

**Comment by AlexRaeside** [comment]
I am running into the same problem with example tables. I imagine it must be ether problems with my input or perhaps my python environment.  
Thank you so for helping me.

python ~/bioTools/JACKS/jacks/run_JACKS.py example_count_data.tab example_repmap_matched_ctrls.tab example_count_data.tab --ctrl_sample_hdr Control
[2019-05-24 10:51:43,284] jacks: INFO     Loading sample specification
[2019-05-24 10:51:43,285] jacks: INFO     Loading gene mappings
Traceback (most recent call last):
  File "/home/alexander/bioTools/JACKS/jacks/run_JACKS.py", line 7, in <module>
    runJACKSFromArgs()
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 441, in runJACKSFromArgs
    args.outprefix, args.reffile, args.n_pseudo, args.count_prior)
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 429, in runJACKS
    ignore_blank_genes, outprefix, reffile)
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 352, in preprocess
    gene_spec = createGeneSpec(guidemappingfile, sgrna_hdr, gene_hdr, ignore_blank_genes=ignore_blank_genes)
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 225, in createGeneSpec
    gene_spec = {row[sgrna_hdr]: row[gene_hdr] for row in rdr if (not ignore_blank_genes or row[gene_hdr] != '')}
  File "/home/alexander/bioTools/JACKS/jacks/jacks/jacks_io.py", line 225, in <dictcomp>
    gene_spec = {row[sgrna_hdr]: row[gene_hdr] for row in rdr if (not ignore_blank_genes or row[gene_hdr] != '')}
KeyError: 'Gene'

Thank again.

**Comment by felicityallen** [comment]
In the example, the header of the gene column is 'gene' not 'Gene', so you'll need to add --gene_hdr=gene
The recommended command for running the example is:

python run_JACKS.py example/example_count_data.tab example/example_repmap.tab example/example_count_data.tab --common_ctrl_sample=CTRL --gene_hdr=gene --outprefix=example_jacks/example_jacks --ctrl_genes=example/NEGv1.txt

**Comment by AlexRaeside** [comment]
This worked!

Thank you for the help and thank you for the program.
